// Build-time data helpers for blog MDX components. The archive JSONs are
// generated by scripts/build-archive.mjs into public/data/archive/ and are
// gitignored, so all access is via Node fs at build time.

import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ARCHIVE_ROOT = resolve(process.cwd(), 'public/data/archive');

let driverIndexCache: DriverIndexEntry[] | null = null;

export interface DriverIndexEntry {
  driverRef: string;
  code: string | null;
  forename: string;
  surname: string;
  nationality: string | null;
  firstYear: number;
  lastYear: number;
  races: number;
  wins: number;
  championships: number;
  teamName: string | null;
  teamRef: string | null;
  teamColor: string | null;
  number: string | null;
}

export interface RaceResultEntry {
  position: number | null;
  positionText: string;
  driverRef: string;
  driverName: string;
  code: string | null;
  constructorRef: string | null;
  constructorName: string | null;
  constructorColor: string | null;
  grid: number | null;
  points: number;
  laps: number;
  time: string | null;
  status: string;
}

export interface RaceArchive {
  raceId: string;
  year: number;
  round: number;
  name: string;
  date: string;
  pole: string | null;
  fastestLapTime: string | null;
  winner: string;
  circuit: {
    circuitRef: string;
    name: string;
    country: string;
    countryName: string;
    flag: string;
  };
  results: RaceResultEntry[];
}

export interface DriverArchiveRace {
  year: number;
  round: number;
  raceName: string;
  date: string;
  constructorRef: string | null;
  constructorName: string | null;
  grid: number | null;
  position: number | null;
  points: number;
  status: string | null;
}

export interface DriverArchive {
  driverRef: string;
  forename: string;
  surname: string;
  nationality: string | null;
  career: {
    seasons: number;
    firstYear: number | null;
    lastYear: number | null;
    races: number;
    wins: number;
    podiums: number;
    poles: number;
    championships: number;
  };
  perRace: DriverArchiveRace[];
}

export function getDriverIndex(): DriverIndexEntry[] {
  if (driverIndexCache) return driverIndexCache;
  const path = resolve(ARCHIVE_ROOT, '_drivers-index.json');
  driverIndexCache = JSON.parse(readFileSync(path, 'utf8'));
  return driverIndexCache!;
}

export function getDriverEntry(driverRef: string): DriverIndexEntry | null {
  return getDriverIndex().find((d) => d.driverRef === driverRef) ?? null;
}

export function getDriverArchive(driverRef: string): DriverArchive | null {
  const path = resolve(ARCHIVE_ROOT, `drivers/${driverRef}.json`);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function getRaceArchive(year: number, round: number): RaceArchive | null {
  const path = resolve(ARCHIVE_ROOT, `races/${year}/${round}.json`);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf8'));
}
