// Build a URL → lastmod date map for the @astrojs/sitemap `serialize` hook.
// Loaded from astro.config.mjs at build time. Reads the same archive
// indexes that build-archive.mjs produces, plus blog frontmatter, so
// every prerendered URL signals when its underlying data last changed.
//
// Inputs (all in public/data/archive/, generated by scripts/build-archive.mjs):
//   _races-index.json    - { year, round, date, completed, ... }[]
//   _drivers-index.json  - includes a last5 array of recent race entries
//   _teams-index.json    - same shape as drivers
//   _circuits-index.json - per-circuit metadata; for actual dates we read
//                          the per-circuit doc which carries a races array
//
// Blog posts come from src/content/blog/*.mdx - we parse `updatedAt`/
// `publishedAt` from frontmatter via regex (cheap, no MDX compiler).
//
// Anything not in the map is left without a lastmod tag - the sitemap
// integration emits `<loc>` only for those, which is a valid sitemap.

import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';

const ORIGIN = 'https://f1gures.app';

function readJsonSafe(path) {
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

function endOfYear(year) {
  return year ? `${year}-12-31` : null;
}

// Walk a list of { year, round } refs and resolve each to the race date
// via the (year, round) → date map. Returns the maximum date string (ISO
// dates sort lexicographically), or null if no entry resolved.
function maxRaceDate(entries, raceByRound) {
  if (!Array.isArray(entries) || entries.length === 0) return null;
  let max = null;
  for (const e of entries) {
    const d = raceByRound.get(`${e.year}-${e.round}`);
    if (d && (!max || d > max)) max = d;
  }
  return max;
}

// Pure: build the URL → lastmod map from already-loaded inputs.
// Exported separately so it can be unit-tested without filesystem access.
export function computeLastmodMap({ races = [], drivers = [], teams = [], circuits = [], circuitDocs = {}, blogPosts = [], recordTopics = [], buildDate }) {
  const map = new Map();
  const today = (buildDate || new Date().toISOString().slice(0, 10));

  const raceByRound = new Map();
  for (const r of races) {
    if (r.date) raceByRound.set(`${r.year}-${r.round}`, r.date);
  }

  // Races: completed → race date, upcoming → today (page reflects latest schedule).
  for (const r of races) {
    const lastmod = r.completed && r.date ? r.date : today;
    map.set(`${ORIGIN}/races/${r.year}/${r.round}/`, lastmod);
  }

  // Drivers: max of last5 race dates, fall back to lastYear.
  for (const d of drivers) {
    const lastmod = maxRaceDate(d.last5, raceByRound) || endOfYear(d.lastYear);
    if (lastmod) map.set(`${ORIGIN}/drivers/${d.driverRef}/`, lastmod);
  }

  // Teams: same logic as drivers.
  for (const t of teams) {
    const lastmod = maxRaceDate(t.last5, raceByRound) || endOfYear(t.lastYear);
    if (lastmod) map.set(`${ORIGIN}/teams/${t.constructorRef}/`, lastmod);
  }

  // Circuits: read the per-circuit doc for its full races list and take
  // the most recent date. Index only has years, not dates.
  for (const c of circuits) {
    const doc = circuitDocs[c.circuitRef];
    let max = null;
    if (doc && Array.isArray(doc.races)) {
      for (const r of doc.races) {
        if (r.date && (!max || r.date > max)) max = r.date;
      }
    }
    const lastmod = max || endOfYear(c.lastYear);
    if (lastmod) map.set(`${ORIGIN}/circuits/${c.circuitRef}/`, lastmod);
  }

  // Blog posts: updatedAt wins over publishedAt.
  for (const p of blogPosts) {
    const d = (p.updatedAt || p.publishedAt || '').slice(0, 10);
    if (d) map.set(`${ORIGIN}/blog/${p.slug}/`, d);
  }

  // Listing + static pages: latest completed race date (signals "this is
  // as fresh as the data gets"). Falls back to today if no races.
  const latestRaceDate = races
    .filter(r => r.completed && r.date)
    .map(r => r.date)
    .sort()
    .pop() || today;

  const listingPaths = [
    '/',
    '/calendar/',
    '/circuits/',
    '/teams/',
    '/drivers/',
    '/standings-drivers/',
    '/standings-constructors/',
    '/records/',
    '/blog/',
  ];
  for (const p of listingPaths) {
    map.set(ORIGIN + p, latestRaceDate);
  }

  // Records sub-pages (one per leaderboard topic) refresh whenever the
  // underlying career stats do, i.e. on every completed race.
  for (const topic of recordTopics) {
    map.set(`${ORIGIN}/records/${topic}/`, latestRaceDate);
  }

  // Blog category indexes - newest post in that category.
  const newestByCategory = new Map();
  for (const p of blogPosts) {
    if (!p.category) continue;
    const d = (p.updatedAt || p.publishedAt || '').slice(0, 10);
    if (!d) continue;
    const cur = newestByCategory.get(p.category);
    if (!cur || d > cur) newestByCategory.set(p.category, d);
  }
  for (const [cat, d] of newestByCategory) {
    map.set(`${ORIGIN}/blog/category/${cat}/`, d);
  }

  return map;
}

// Filesystem wrapper used by astro.config.mjs at build time.
export function buildLastmodMap({ cwd = process.cwd() } = {}) {
  const ARCHIVE = resolve(cwd, 'public/data/archive');
  const CONTENT = resolve(cwd, 'src/content/blog');

  const races = readJsonSafe(join(ARCHIVE, '_races-index.json')) || [];
  const drivers = readJsonSafe(join(ARCHIVE, '_drivers-index.json')) || [];
  const teams = readJsonSafe(join(ARCHIVE, '_teams-index.json')) || [];
  const circuits = readJsonSafe(join(ARCHIVE, '_circuits-index.json')) || [];

  const circuitDocs = {};
  for (const c of circuits) {
    const doc = readJsonSafe(join(ARCHIVE, 'circuits', `${c.circuitRef}.json`));
    if (doc) circuitDocs[c.circuitRef] = doc;
  }

  const blogPosts = [];
  if (existsSync(CONTENT)) {
    for (const f of readdirSync(CONTENT)) {
      if (!/\.(mdx|md)$/.test(f)) continue;
      const raw = readFileSync(join(CONTENT, f), 'utf8');
      const slug = f.replace(/\.(mdx|md)$/, '');
      const updatedAt = raw.match(/^updatedAt:\s*(.+)$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '');
      const publishedAt = raw.match(/^publishedAt:\s*(.+)$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '');
      const category = raw.match(/^category:\s*(.+)$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '');
      blogPosts.push({ slug, updatedAt, publishedAt, category });
    }
  }

  // Records: flatten { groups: [{ records: [{ id }] }] } into a flat list
  // of topic ids matching the /records/[topic].astro routes.
  const recordsIdx = readJsonSafe(join(ARCHIVE, '_records-index.json'));
  const recordTopics = [];
  if (recordsIdx && Array.isArray(recordsIdx.groups)) {
    for (const g of recordsIdx.groups) {
      for (const r of g.records || []) {
        if (r.id) recordTopics.push(r.id);
      }
    }
  }

  return computeLastmodMap({ races, drivers, teams, circuits, circuitDocs, blogPosts, recordTopics });
}
