// scripts/social/sources.mjs
//
// Read-only, memoized accessors over the build artefacts the social-post
// pipeline draws on. Everything here is derived data that already exists on
// disk after `npm run build:archive` - the pipeline invents nothing, which is
// what makes unattended daily posting safe.
//
// All paths use resolve(ROOT, ...) rather than import.meta.url tricks so this
// behaves identically whether it is imported from a script or a test.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const ROOT = path.resolve(__dirname, '../..');
export const ARCHIVE = path.join(ROOT, 'public/data/archive');

const cache = new Map();

function readJson(abs, fallback = null) {
  if (cache.has(abs)) return cache.get(abs);
  let value = fallback;
  try {
    value = JSON.parse(fs.readFileSync(abs, 'utf8'));
  } catch {
    value = fallback;
  }
  cache.set(abs, value);
  return value;
}

/** Clear the memo cache. Tests use this between fixtures. */
export function resetCache() {
  cache.clear();
}

/**
 * The archive is gitignored and regenerated by prebuild. Everything downstream
 * assumes it exists, so fail loudly and actionably rather than silently
 * producing an empty post.
 */
export function assertArchive() {
  if (!fs.existsSync(path.join(ARCHIVE, '_races-index.json'))) {
    throw new Error(
      'public/data/archive/ is missing or incomplete - run `npm run build:archive` first.',
    );
  }
}

// ── indexes ──
export const racesIndex = () => readJson(path.join(ARCHIVE, '_races-index.json'), []);
export const driversIndex = () => readJson(path.join(ARCHIVE, '_drivers-index.json'), []);
export const teamsIndex = () => readJson(path.join(ARCHIVE, '_teams-index.json'), []);
export const circuitsIndex = () => readJson(path.join(ARCHIVE, '_circuits-index.json'), []);
export const recordsIndex = () => readJson(path.join(ARCHIVE, '_records-index.json'), { groups: [] });
export const seasons = () => readJson(path.join(ARCHIVE, '_seasons.json'), {});
export const compareSuggestions = () =>
  readJson(path.join(ARCHIVE, '_compare-suggestions.json'), { driver: [], team: [] });

// ── documents ──
export const raceDoc = (year, round) =>
  readJson(path.join(ARCHIVE, 'races', String(year), `${round}.json`));
export const driverDoc = (ref) => (ref ? readJson(path.join(ARCHIVE, 'drivers', `${ref}.json`)) : null);
export const teamDoc = (ref) => (ref ? readJson(path.join(ARCHIVE, 'teams', `${ref}.json`)) : null);
export const circuitDoc = (ref) => (ref ? readJson(path.join(ARCHIVE, 'circuits', `${ref}.json`)) : null);
export const recordDoc = (topic) => (topic ? readJson(path.join(ARCHIVE, 'records', `${topic}.json`)) : null);

// ── non-archive data ──
export const trivia = () => readJson(path.join(ROOT, 'src/data/trivia.json'), { facts: [] });
export const seasonBundle = (year) => readJson(path.join(ROOT, `public/data/${year}.json`));

/** Flat list of every record config the hub knows about, with its group label. */
export function recordConfigs() {
  const out = [];
  for (const group of recordsIndex().groups || []) {
    for (const rec of group.records || []) out.push({ ...rec, groupId: group.id, groupLabel: group.label });
  }
  return out;
}

/** driverRef -> index row, for cheap "is this driver notable" lookups. */
export function driverIndexMap() {
  const key = '__driverIndexMap';
  if (cache.has(key)) return cache.get(key);
  const map = new Map(driversIndex().map((d) => [d.driverRef, d]));
  cache.set(key, map);
  return map;
}

/** circuitRef -> index row. */
export function circuitIndexMap() {
  const key = '__circuitIndexMap';
  if (cache.has(key)) return cache.get(key);
  const map = new Map(circuitsIndex().map((c) => [c.circuitRef, c]));
  cache.set(key, map);
  return map;
}

/** teamRef -> index row. */
export function teamIndexMap() {
  const key = '__teamIndexMap';
  if (cache.has(key)) return cache.get(key);
  const map = new Map(teamsIndex().map((t) => [t.constructorRef, t]));
  cache.set(key, map);
  return map;
}

/** Races grouped by MM-DD, for the "on this day" angle. */
export function racesByMonthDay() {
  const key = '__racesByMonthDay';
  if (cache.has(key)) return cache.get(key);
  const map = new Map();
  for (const r of racesIndex()) {
    if (!r.date || !r.completed) continue;
    const md = r.date.slice(5, 10);
    if (!map.has(md)) map.set(md, []);
    map.get(md).push(r);
  }
  cache.set(key, map);
  return map;
}
